### ISSUE TITLE
Make docker publish workflow an option in set up prompts

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/python-template#55]
The publish workflow currently includes some commented-out code that would be better of an an optional workflow determined by the prompts

**Comment by AdrianDAlessandro** [comment]
I recently noticed some issues with sensibly tagging docker images built from releases. Mainly that even releases tagged as "pre-release" result in an image with the "latest" tag and that release workflow run three times unless you restrict it to `published` only.

I made some changes to the release workflow in [this PR in Gridlington-Vis](https://github.com/ImperialCollegeLondon/gridlington-vis/pull/117) that resolve those two issues.

**Comment by alexdewar** [comment]
Following discussion, we've decided not to implement this for now.
