### ISSUE TITLE
Update LICENSEs to match Imperial Recommendations

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/python-template#84]
Both license files have a copyright message of "Copyright (c) 2024, Alex Dewar" when they should have "Copyright (c) 2023, Imperial College London. All rights reserved." according to [Imperial Guidelines](https://imperiallondon.sharepoint.com/sites/ente/Gov/PoliciesandGuidanceforImperialStaff/Forms/AllItems.aspx?id=%2Fsites%2Fente%2FGov%2FPoliciesandGuidanceforImperialStaff%2FImperial%5FEnterprise%5FOpen%20Source%20Software%20Licences%5FAug23%2Epdf&parent=%2Fsites%2Fente%2FGov%2FPoliciesandGuidanceforImperialStaff)

Maybe the one built by cookiecutter should use the Author name?

**Comment by alexdewar** [comment]
Oops! Yes, it shouldn't be copyrighted to me (I set up the repo on my own account originally, so I guess GitHub just used my name for it).

I guess we *could* use the author's name, but if they're planning on putting it on the `ImperialCollegeLondon` org then I suppose it should also be copyrighted to ICL. Either way, it shouldn't say my name though, so I might just use the author's name for now as it's better than what we currently have.
