### ISSUE TITLE
Make test CI workflow require pre-commit to pass before it runs

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/python-template#85]

**Comment by alexdewar** [comment]
I'm not sure this is a problem... There's a separate workflow for running `pre-commit` so users will need to add this check to their branch protection rule (if they're using it). But I don't think we need to make running the tests dependent on the `pre-commit` checks passing. They are different checks, after all.

Have I misunderstood something @AdrianDAlessandro?

**Comment by AdrianDAlessandro** [comment]
> Have I misunderstood something @AdrianDAlessandro?

No. I think I put this in because that's how we had it in other repos (ie follow the "fail fast" approach). But this gets very difficult/impossible to do if using pre-commit.ci instead of a custom action.

I agree I don't think this is needed, nor does it add any value.
